### ISSUE TITLE
VkOreonworlds crashes when maximized

### ISSUE THREAD

**Issue by aromanelli** [oreonengine/oreon-engine#44]
When trying to maximize the Vulkan demo, either by double-clicking on its title, or by clicking on the maximize button on the window title, the program crashes with the following console output ...

> Exception in thread "main" java.lang.AssertionError: A surface has changed in such a way that it is no longer compatible with the swapchain, and further presentation requests using the swapchain will fail. Applications must query the new surface properties and recreate their swapchain if they wish to continuepresenting to the surface.
> 	at org.oreon.core.vk.util.VkUtil.vkCheckResult(VkUtil.java:61)
> 	at org.oreon.core.vk.swapchain.SwapChain.draw(SwapChain.java:298)
> 	at org.oreon.vk.engine.VkRenderEngine.render(VkRenderEngine.java:351)
> 	at org.oreon.core.system.CoreSystem.render(CoreSystem.java:40)
> 	at org.oreon.core.system.CoreEngine.render(CoreEngine.java:97)
> 	at org.oreon.core.system.CoreEngine.run(CoreEngine.java:71)
> 	at org.oreon.core.system.CoreEngine.start(CoreEngine.java:26)
> 	at org.oreon.examples.vk.oreonworlds.VkOreonworlds.main(VkOreonworlds.java:30)

I set a breakpoint at VkUtil.vkCheckResult(int), and the error code passed in is "-1000001004".  Here's the info (screenshot of my IDE in debug mode) showing the vkCheckResult method being called, that genertes the assert failure ...

![oreonengine ij breakpoint](https://user-images.githubusercontent.com/409304/45247940-6901f100-b2c0-11e8-84f6-9ca76e7c780c.png)

My OS is Ubuntu Budgie 18.04.1 LTS (64-bit), using Gnome 3.28.2. Processor is Intel Core i7 CPU 980 @ 3.33GHz x 12, with 24GB RAM. I'm using a GigaBytte GeForce GTX 1050 OC Edition, with 2GB GDDR5 (PCIe/SSE2). Its a DirectX 12 ready card, and is six months old.  Using the open-source version of the nvidia driver: [Video Driver Information](https://user-images.githubusercontent.com/409304/44949162-0486f380-ade1-11e8-9998-f0d1328647d5.png)

As an aside, the GLOreonworlds demo does not crash, but the world viewport size does not enlarge to meet the size of the window frame, that is now maximized.  The world viewport keeps the pre-maximize size.

**Comment by oreonengine** [comment]
Yes I will fix this, it crashes because the swapchain and some Vulkan pipelines etc. which access screen width and height must be explicitly recreated after resizing the window.
